### ISSUE TITLE
🌟 [feat] 보드 수정 기능 구현

### ISSUE THREAD

**Issue by ggumi030** [spartaKanbanBoard/spartaKanbanBoard#10]
**🌟 Issue : Feature**
보드 수정 기능 구현

**Description**
보드 이름, 한 줄 설명 필수 데이터를 수정할 수 있습니다.

**Todo**
- [x] 보드 수정 기능 구현
- [x] 예외처리 : 권한에 맞지 않는 사용자가 수정을 시도하는 경우
- [x] 예외처리 : 보드 이름, 한 줄 설명 필수 데이터가 존재하지 않는 경우

**Reference(Optional)**
Amdin만 해당 기능을 사용할 수 있습니다.
